//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourcesLibrary.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to center.
        /// </summary>
        internal static string AlignToastrCenter {
            get {
                return ResourceManager.GetString("AlignToastrCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string AlignToastrLeft {
            get {
                return ResourceManager.GetString("AlignToastrLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string AlignToastrRight {
            get {
                return ResourceManager.GetString("AlignToastrRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been deleted successfully.
        /// </summary>
        internal static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error backing up file.
        /// </summary>
        internal static string ErrorBackingUpFile {
            get {
                return ResourceManager.GetString("ErrorBackingUpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to add the record. The dates overlap with other records.
        /// </summary>
        internal static string ErrorDatesOverlapping {
            get {
                return ResourceManager.GetString("ErrorDatesOverlapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to add the record. The dates are out of the valid date range.
        /// </summary>
        internal static string ErrorInvalidDatesToAssign {
            get {
                return ResourceManager.GetString("ErrorInvalidDatesToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to add the record. Expiration date must be more than Effective date.
        /// </summary>
        internal static string ErrorInvalidEffective {
            get {
                return ResourceManager.GetString("ErrorInvalidEffective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string ErrorTypeToastr {
            get {
                return ResourceManager.GetString("ErrorTypeToastr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error processing your request, please try again later.
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        internal static string InfoTypeToastr {
            get {
                return ResourceManager.GetString("InfoTypeToastr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone extension format is invalid .
        /// </summary>
        internal static string InvalidPhoneExtension {
            get {
                return ResourceManager.GetString("InvalidPhoneExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The register already exists.
        /// </summary>
        internal static string RegisterAlreadyExists {
            get {
                return ResourceManager.GetString("RegisterAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        internal static string SuccessTypeToastr {
            get {
                return ResourceManager.GetString("SuccessTypeToastr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string TimeToastr {
            get {
                return ResourceManager.GetString("TimeToastr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        internal static string WarningTypeToastr {
            get {
                return ResourceManager.GetString("WarningTypeToastr", resourceCulture);
            }
        }
    }
}
