//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourcesLibrary.Resources.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string HeaderError {
            get {
                return ResourceManager.GetString("HeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string HeaderSuccess {
            get {
                return ResourceManager.GetString("HeaderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error.
        /// </summary>
        internal static string msjErrorGeneric {
            get {
                return ResourceManager.GetString("msjErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending mail.
        /// </summary>
        internal static string msjErrorSendMail {
            get {
                return ResourceManager.GetString("msjErrorSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Saved.
        /// </summary>
        internal static string msjHeaderSuccess {
            get {
                return ResourceManager.GetString("msjHeaderSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user Password has been reset.
        /// </summary>
        internal static string msjResetPassSuccess {
            get {
                return ResourceManager.GetString("msjResetPassSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol was created.
        /// </summary>
        internal static string msjRolCreate {
            get {
                return ResourceManager.GetString("msjRolCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role has been removed.
        /// </summary>
        internal static string msjRolDelete {
            get {
                return ResourceManager.GetString("msjRolDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error obtaining Roles.
        /// </summary>
        internal static string msjRolesError {
            get {
                return ResourceManager.GetString("msjRolesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The role has been updated.
        /// </summary>
        internal static string msjRolUpdate {
            get {
                return ResourceManager.GetString("msjRolUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was saved successfully.
        /// </summary>
        internal static string msjUserCreate {
            get {
                return ResourceManager.GetString("msjUserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was deleted successfully.
        /// </summary>
        internal static string msjUserDelete {
            get {
                return ResourceManager.GetString("msjUserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error obtaining Users.
        /// </summary>
        internal static string msjUsersError {
            get {
                return ResourceManager.GetString("msjUsersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was saved successfully.
        /// </summary>
        internal static string msjUserUpdate {
            get {
                return ResourceManager.GetString("msjUserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user will need to login again to see the change.
        /// </summary>
        internal static string msjUserUpdateLogout {
            get {
                return ResourceManager.GetString("msjUserUpdateLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string TimeToaster {
            get {
                return ResourceManager.GetString("TimeToaster", resourceCulture);
            }
        }
    }
}
